repos:
- repo: git@github.com:pre-commit/pre-commit-hooks
  sha: v1.1.1
  hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: detect-aws-credentials
      args: ["--allow-missing-credentials"]
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: '(?:.*[\\/])?\.bumpversion\.cfg$'
    - id: flake8
    - id: trailing-whitespace
      exclude: '(?:.*[\\/])?\.bumpversion\.cfg$'
