[tool.poetry]
name = "pytest-localstack"
version = "0.7.0"
description = "Pytest plugin for AWS integration tests"
authors = ["Mintel Group Ltd."]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/mintel/pytest-localstack"
documentation = "https://pytest-localstack.readthedocs.io/"
keywords = ["pytest", "localstack", "aws"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Testing",
    "Topic :: Utilities",
]
include = ["CHANGELOG.rst", "LICENSE"]

[tool.poetry.plugins.pytest11]
localstack = "pytest_localstack"

[tool.poetry.dependencies]
python = "^3.10"
botocore = ">=1.23.0"
docker = ">=7.1.0"
pluggy = ">=1.0.0"
pytest = ">=7"

[tool.poetry.group.dev.dependencies]
boto3 = "^1.43.74"
hypothesis = "^6.165.10"
black = "^26.5.1"
isort = "^5.8.0"
mypy = "^1.0.1"
flake8 = "^7.3.0"
bandit = "^1.7.5"
pyyaml = "^6.0.3"
coverage = {extras = ["toml"], version = "^7.10.7"}
codecov = "^2.1.13"
pytest-cov = "^7.1.0"
pytest-timeout = "^2.4.0"
pytest-xdist = "^3.8.0"
sphinx = "^4.5.0"
flake8-pyproject = "^1.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
norecursedirs = ".* build dist *.egg tmp*"
testpaths = "tests/unit tests/integration tests/functional pytest_localstack examples"
timeout = 300
addopts = "--doctest-glob='*.rst' --doctest-glob='*.md' --doctest-modules"

[tool.isort]
skip_glob = "*/.venv/*"
profile = "black"

# Structure
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "TESTING", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
known_testing = ["hypothesis", "pytest", "tests"]
known_first_party = ["pytest_localstack"]

[tool.flake8]
max-line-length = 88 # Black line length.
extend-ignore = "W503,E501"

[tool.coverage.run]
omit = ["pytest_localstack/hookspecs.py"]
